source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

target "StatsDemo" do
  pod 'WordPressCom-Stats-iOS', :path => '../'
end

target "StatsDemo-Internal" do
    pod 'WordPressCom-Stats-iOS', :path => '../'
    pod 'HockeySDK'
end
