source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

abstract_target 'StatsDemo_Abstract' do
  pod 'WordPressCom-Stats-iOS', :path => '../'
  pod 'HockeySDK'
  
  target "StatsDemo" do
  end

  target "StatsDemo Internal" do
  end
end
