#import "WPSViewController.h"
#import <WPStatsViewController.h>
#import <StatsTableViewController.h>

@interface WPSViewController ()

@property (nonatomic, strong) WPStatsViewController *statsViewController;

@end

@implementation WPSViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
#warning You have to replace the site ID & OAuth2 token with one generated by the WP.com API
//    self.statsViewController = [[WPStatsViewController alloc] initWithSiteID:nil siteTimeZone:nil andOAuth2Token:nil];
    
    id viewController = [[UIStoryboard storyboardWithName:@"SiteStats" bundle:nil] instantiateInitialViewController];
    
    [self addChildViewController:viewController];
    [self.view addSubview:[viewController view]];
}

- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

@end
