#import "WPSViewController.h"
#import <StatsTableViewController.h>

@implementation WPSViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    UINavigationController *navController = [[UIStoryboard storyboardWithName:@"SiteStats" bundle:nil] instantiateInitialViewController];
    StatsTableViewController *statsViewController = (StatsTableViewController *)[navController topViewController];
#warning You have to replace the site ID, timezone & OAuth2 token with one generated by the WP.com API
    statsViewController.siteID = nil;
    statsViewController.siteTimeZone = [NSTimeZone timeZoneWithName:@"America/Chicago"];
    statsViewController.oauth2Token = nil;
    
    [self addChildViewController:navController];
    [self.view addSubview:[navController view]];
}

@end
